config/routes.rb
Rails.application.routes.draw do
  get "demo/index"
  get 'civil_project/new_form', to: 'civil_project#new', as: 'new_civil_project_form'

  resources :civil_project, only: [:new, :create, :show]  # root "demo#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/civil_project.rb
class CivilProject < ApplicationRecord
    validates :title, presence: true, length: { minimum: 5 }
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/civil_project_controller.rb
class CivilProjectController < ActionController::Base 

    #  before_action :find_civil_project, only: [:create]
    def new
        @createData = CivilProject.new
      end
    def create
        @createDataa = CivilProject.new(project_params);
        if @project.save
            redirect_to @project, notice: 'Project was successfully created.'
        else
            render :new
        end
    end

    def show 
    end 

    def index 
    end 
    private 

    
    def project_params
        params.require(:civil_project).permit(:title, :description, :image_path, :video_path)
      end
      
end     

app/controllers/demo_controller.rb
class DemoController < ActionController::Base

    def index 
        @data = CivilProject.all;
        puts(@data);
    end 


    def show 
        @showTitle = "here we go"
    end     

    def create 
    end 

    def new 
    end 

    private 

    def finding_id 
    end 
                                    
   
end     

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/civil_project/new.html.erb
<h1>Create Civil Project</h1>

<%= form_with(model: @createData, url: civil_project_path, method: :post) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title, required: true %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description, required: true %>
  </div>

  <div>
    <%= form.label :image_path %>
    <%= form.text_field :image_path %>
  </div>

  <div>
    <%= form.label :video_path %>
    <%= form.text_field :video_path %>
  </div>

  <div class="actions">
    <%= form.submit "Create Project" %>
  </div>
<% end %>

app/views/civil_project/show.html.erb
<h1> sunil varma </h1>

app/views/demo/index.html.erb
<h1> Civil Projects index  </h1>

<form action="/civil_projects" method="post">
    <!-- CSRF Token for security -->
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label for="title">Title:</label>
    <input type="text" id="title" name="civil_project[title]" required>

    <label for="description">Description:</label>
    <textarea id="description" name="civil_project[description]" required></textarea>

   

    <button type="submit">Submit</button>
  </form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "civil_project/show" %> 

    <%= yield %>

  </body>
</html>